version: "3.7"
services:
  node:
    build: .
    container_name: front_end_links
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - .:/usr/app
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "10m" # file size
networks:
  default:
    name: rede
    external: true